# Generated by Django 2.1.5 on 2020-01-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200120_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
